### ISSUE TITLE
Selection on another field

### ISSUE THREAD

**Issue by paulcalvet** [murraygm/qse-mgoimagegrid#4]
Hi,
This extension is really great.
I think it will be better if we can choose to select a field which is linked to the image.
For example, I have 
   - a field "Product Universe" (which is a master item) 
   - and another field "Product universe image" (which contains the images). 
When the user makes a selection in the extension, Qlik Sense make a selection on the field "Product universe image". In the selection bar, the selection on "Product Universe" doesn't appears but the user doesn't know why (because in his mind he select a Product Universe)
It is possible to add an option to make the selection on the field "Product Universe" ?

Thanks for your work and your contribution to the Qlik community :-)

Paul

**Comment by murraygm** [comment]
Thanks Paul great suggestion. The image field ref as the selected value has
also felt a little odd. Adding a secondary for the 'actual' selection would
be a neat trick. I'll look into it, unfortunately I can't promise anything
anytime soon.

Sent from my iPhone

On May 10, 2017, at 13:51, paulcalvet <notifications@github.com> wrote:

Hi,
This extension is really great.
I think it will be better if we can choose to select a field which is
linked to the image.
For example, I have

   - a field "Product Universe" (which is a master item)
   - and another field "Product universe image" (which contains the images).
   When the user makes a selection in the extension, Qlik Sense make a
   selection on the field "Product universe image". In the selection bar, the
   selection on "Product Universe" doesn't appears but the user doesn't know
   why (because in his mind he select a Product Universe)
   It is possible to add an option to make the selection on the field
   "Product Universe" ?

Thanks for your work and your contribution to the Qlik community :-)

Paul

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/murraygm/qse-mgoimagegrid/issues/4>, or mute the thread

**Comment by murraygm** [comment]
Added the ability to make the selection in the 2nd dimension - in v3.11

**Comment by paulcalvet** [comment]
Many thanks ! 
it's cool, user can now select dimension with your extension !
